name: Build and test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  full_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        toolchain: [ stable, 1.70.0 ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup rust version
        run: rustup default ${{ matrix.toolchain }}

      - name: Clippy fmt
        run: |
          cargo fmt -- --check
        if: ${{ matrix.type == 'stable' }}

      - name: Cargo check
        run: |
          cargo check
          cargo check --all-features

      - name: Cargo check examples
        run: |
          cargo check --examples
          cargo check --examples --all-features

      - name: Clippy pedantic
        run: |
          cargo clippy -- -W clippy::pedantic -A clippy::module-name-repetitions -A clippy::missing-errors-doc -A clippy::inline_always -A clippy::wildcard-imports -A clippy::cast_possible_truncation -A clippy::cast-precision-loss
        if: ${{ matrix.type == 'stable' }}

      - name: Test
        run: |
          cargo test --no-fail-fast -- --nocapture
          cargo test --all-features --no-fail-fast -- --nocapture

      - name: Doc
        run: |
          cargo doc

      - name: Cargo release
        run: |
          cargo build --release

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: system_info_collector-${{ matrix.os }}-${{ matrix.toolchain }}
          path: target/release